// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: idssschema.proto

package main

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryManager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdQuery        int32                `protobuf:"varint,1,opt,name=id_query,json=idQuery,proto3" json:"id_query,omitempty"`                      // Autoincrement
	Uqid           int64                `protobuf:"varint,2,opt,name=uqid,proto3" json:"uqid,omitempty"`                                           // Unique Query ID, generated by the client
	Query          string               `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`                                          // Query in eliasdb
	Ttl            int64                `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`                                             // Time to live in seconds
	ArrivedAt      *timestamp.Timestamp `protobuf:"bytes,5,opt,name=arrived_at,json=arrivedAt,proto3" json:"arrived_at,omitempty"`                 // Timestamp when the query arrived
	SenderId       string               `protobuf:"bytes,6,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                    // Client ID
	LocalExecution int32                `protobuf:"varint,7,opt,name=local_execution,json=localExecution,proto3" json:"local_execution,omitempty"` // 0 = false, 1 = true
	Completed      bool                 `protobuf:"varint,8,opt,name=completed,proto3" json:"completed,omitempty"`                                 // 0 = false, 1 = true
	SentBack       bool                 `protobuf:"varint,9,opt,name=sent_back,json=sentBack,proto3" json:"sent_back,omitempty"`                   // 0 = false, 1 = true
	Failed         bool                 `protobuf:"varint,10,opt,name=failed,proto3" json:"failed,omitempty"`                                      // 0 = false, 1 = true
}

func (x *QueryManager) Reset() {
	*x = QueryManager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idssschema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryManager) ProtoMessage() {}

func (x *QueryManager) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryManager.ProtoReflect.Descriptor instead.
func (*QueryManager) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{0}
}

func (x *QueryManager) GetIdQuery() int32 {
	if x != nil {
		return x.IdQuery
	}
	return 0
}

func (x *QueryManager) GetUqid() int64 {
	if x != nil {
		return x.Uqid
	}
	return 0
}

func (x *QueryManager) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryManager) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *QueryManager) GetArrivedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ArrivedAt
	}
	return nil
}

func (x *QueryManager) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *QueryManager) GetLocalExecution() int32 {
	if x != nil {
		return x.LocalExecution
	}
	return 0
}

func (x *QueryManager) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *QueryManager) GetSentBack() bool {
	if x != nil {
		return x.SentBack
	}
	return false
}

func (x *QueryManager) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId       int32  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientName     string `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ContractNumber int64  `protobuf:"varint,3,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`
	Power          int32  `protobuf:"varint,4,opt,name=power,proto3" json:"power,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idssschema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{1}
}

func (x *Client) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Client) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Client) GetContractNumber() int64 {
	if x != nil {
		return x.ContractNumber
	}
	return 0
}

func (x *Client) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

type Consumption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Measurement float64              `protobuf:"fixed64,2,opt,name=measurement,proto3" json:"measurement,omitempty"`
	Client      *Client              `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *Consumption) Reset() {
	*x = Consumption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idssschema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consumption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consumption) ProtoMessage() {}

func (x *Consumption) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consumption.ProtoReflect.Descriptor instead.
func (*Consumption) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{2}
}

func (x *Consumption) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Consumption) GetMeasurement() float64 {
	if x != nil {
		return x.Measurement
	}
	return 0
}

func (x *Consumption) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

var File_idssschema_proto protoreflect.FileDescriptor

var file_idssschema_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x64, 0x73, 0x73, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x02, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x64, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x71, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x75,
	0x71, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x61,
	0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x61, 0x72, 0x72,
	0x69, 0x76, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65,
	0x6e, 0x74, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73,
	0x65, 0x6e, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22,
	0x85, 0x01, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x8a, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x42, 0x0e, 0x5a, 0x0c, 0x69, 0x64, 0x73, 0x73, 0x2f, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x64, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idssschema_proto_rawDescOnce sync.Once
	file_idssschema_proto_rawDescData = file_idssschema_proto_rawDesc
)

func file_idssschema_proto_rawDescGZIP() []byte {
	file_idssschema_proto_rawDescOnce.Do(func() {
		file_idssschema_proto_rawDescData = protoimpl.X.CompressGZIP(file_idssschema_proto_rawDescData)
	})
	return file_idssschema_proto_rawDescData
}

var file_idssschema_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_idssschema_proto_goTypes = []interface{}{
	(*QueryManager)(nil),        // 0: QueryManager
	(*Client)(nil),              // 1: Client
	(*Consumption)(nil),         // 2: Consumption
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_idssschema_proto_depIdxs = []int32{
	3, // 0: QueryManager.arrived_at:type_name -> google.protobuf.Timestamp
	3, // 1: Consumption.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: Consumption.client:type_name -> Client
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_idssschema_proto_init() }
func file_idssschema_proto_init() {
	if File_idssschema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idssschema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryManager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idssschema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idssschema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consumption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idssschema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idssschema_proto_goTypes,
		DependencyIndexes: file_idssschema_proto_depIdxs,
		MessageInfos:      file_idssschema_proto_msgTypes,
	}.Build()
	File_idssschema_proto = out.File
	file_idssschema_proto_rawDesc = nil
	file_idssschema_proto_goTypes = nil
	file_idssschema_proto_depIdxs = nil
}
