//
// ! \file idssschema.proto
// ! \brief A file that contains the protocol buffer definition for the messages that are exchanged between the nodes in the network.
//
// Copyright 2023-2027, University of Salento, Italy.
// All rights reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: idssschema.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_QUERY                 MessageType = 0 // A query message
	MessageType_RESULT                MessageType = 1 // A result message
	MessageType_CUSTOMER_REGISTRATION MessageType = 2 // A customer registration message
	MessageType_SETTLEMENT_REQUEST    MessageType = 3 // A settlement request message
	MessageType_SETTLEMENT_RESULT     MessageType = 4 // A settlement result message
	MessageType_REGISTRATION_ACK      MessageType = 5 // A community manager's reply to a customer registration
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "QUERY",
		1: "RESULT",
		2: "CUSTOMER_REGISTRATION",
		3: "SETTLEMENT_REQUEST",
		4: "SETTLEMENT_RESULT",
		5: "REGISTRATION_ACK",
	}
	MessageType_value = map[string]int32{
		"QUERY":                 0,
		"RESULT":                1,
		"CUSTOMER_REGISTRATION": 2,
		"SETTLEMENT_REQUEST":    3,
		"SETTLEMENT_RESULT":     4,
		"REGISTRATION_ACK":      5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_idssschema_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_idssschema_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{0}
}

type QueryState_State int32

const (
	QueryState_QUEUED           QueryState_State = 0 // The query is in the queue
	QueryState_LOCALLY_EXECUTED QueryState_State = 1 // The query is executed locally
	QueryState_COMPLETED        QueryState_State = 2 // The query is completed
	QueryState_SENT_BACK        QueryState_State = 3 // Query result is sent back to the parent node
	QueryState_FAILED           QueryState_State = 4 // The query failed
)

// Enum value maps for QueryState_State.
var (
	QueryState_State_name = map[int32]string{
		0: "QUEUED",
		1: "LOCALLY_EXECUTED",
		2: "COMPLETED",
		3: "SENT_BACK",
		4: "FAILED",
	}
	QueryState_State_value = map[string]int32{
		"QUEUED":           0,
		"LOCALLY_EXECUTED": 1,
		"COMPLETED":        2,
		"SENT_BACK":        3,
		"FAILED":           4,
	}
)

func (x QueryState_State) Enum() *QueryState_State {
	p := new(QueryState_State)
	*p = x
	return p
}

func (x QueryState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_idssschema_proto_enumTypes[1].Descriptor()
}

func (QueryState_State) Type() protoreflect.EnumType {
	return &file_idssschema_proto_enumTypes[1]
}

func (x QueryState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryState_State.Descriptor instead.
func (QueryState_State) EnumDescriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{4, 0}
}

// QueryMessage represents a query being propagated in the network
type QueryMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=common.MessageType" json:"type,omitempty"`                                     // To distinguish between QUERY and RESULT.
	Query                string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                                                            // The query to be executed
	Uqid                 string                 `protobuf:"bytes,3,opt,name=uqid,proto3" json:"uqid,omitempty"`                                                              // Unique query identifier
	Timestamp            string                 `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                   // Timestamp of the query
	Ttl                  float32                `protobuf:"fixed32,4,opt,name=ttl,proto3" json:"ttl,omitempty"`                                                              // Time to live
	Sender               string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`                                                          // The peer_id of the sender
	Originator           string                 `protobuf:"bytes,6,opt,name=originator,proto3" json:"originator,omitempty"`                                                  // The peer_id of the originator
	State                *QueryState            `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`                                                            // The state of the query
	Labels               []string               `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`                                                          // The labels of the query
	Result               []*Row                 `protobuf:"bytes,9,rep,name=result,proto3" json:"result,omitempty"`                                                          // The result of the query
	Error                string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`                                                           // Error message if any
	RecordCount          int32                  `protobuf:"varint,12,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`                           // Number of records in the result
	RequesterId          string                 `protobuf:"bytes,13,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`                            // Peer ID of the submitting client
	RequesterRole        string                 `protobuf:"bytes,14,opt,name=requester_role,json=requesterRole,proto3" json:"requester_role,omitempty"`                      // member, manager, or observer
	CustomerRegistration *CustomerRegistration  `protobuf:"bytes,15,opt,name=customer_registration,json=customerRegistration,proto3" json:"customer_registration,omitempty"` // The customer registration details
	SettlementRequest    *SettlementRequest     `protobuf:"bytes,16,opt,name=settlement_request,json=settlementRequest,proto3" json:"settlement_request,omitempty"`          // The settlement request details
	SettlementResult     *SettlementResult      `protobuf:"bytes,17,opt,name=settlement_result,json=settlementResult,proto3" json:"settlement_result,omitempty"`             // The result of the settlement request
	RespondingPeerIds    []string               `protobuf:"bytes,18,rep,name=responding_peer_ids,json=respondingPeerIds,proto3" json:"responding_peer_ids,omitempty"`        // List of peer IDs that have responded to the query
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QueryMessage) Reset() {
	*x = QueryMessage{}
	mi := &file_idssschema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMessage) ProtoMessage() {}

func (x *QueryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMessage.ProtoReflect.Descriptor instead.
func (*QueryMessage) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_QUERY
}

func (x *QueryMessage) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryMessage) GetUqid() string {
	if x != nil {
		return x.Uqid
	}
	return ""
}

func (x *QueryMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *QueryMessage) GetTtl() float32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *QueryMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *QueryMessage) GetOriginator() string {
	if x != nil {
		return x.Originator
	}
	return ""
}

func (x *QueryMessage) GetState() *QueryState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *QueryMessage) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QueryMessage) GetResult() []*Row {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryMessage) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *QueryMessage) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *QueryMessage) GetRequesterRole() string {
	if x != nil {
		return x.RequesterRole
	}
	return ""
}

func (x *QueryMessage) GetCustomerRegistration() *CustomerRegistration {
	if x != nil {
		return x.CustomerRegistration
	}
	return nil
}

func (x *QueryMessage) GetSettlementRequest() *SettlementRequest {
	if x != nil {
		return x.SettlementRequest
	}
	return nil
}

func (x *QueryMessage) GetSettlementResult() *SettlementResult {
	if x != nil {
		return x.SettlementResult
	}
	return nil
}

func (x *QueryMessage) GetRespondingPeerIds() []string {
	if x != nil {
		return x.RespondingPeerIds
	}
	return nil
}

type CustomerRegistration struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mrid             string                 `protobuf:"bytes,1,opt,name=mrid,proto3" json:"mrid,omitempty"`                                                 // The market participant ID
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                 // The name of the customer
	Role             string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                                                 // The role of the customer (e.g., member, manager, observer)
	MembershipStatus string                 `protobuf:"bytes,4,opt,name=membership_status,json=membershipStatus,proto3" json:"membership_status,omitempty"` // The membership status of the customer
	ContractNumber   string                 `protobuf:"bytes,5,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`       // The contract number associated with the customer
	CommunityId      string                 `protobuf:"bytes,6,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`                // Energy community the customer joins (empty: legacy, unscoped registration)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CustomerRegistration) Reset() {
	*x = CustomerRegistration{}
	mi := &file_idssschema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRegistration) ProtoMessage() {}

func (x *CustomerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRegistration.ProtoReflect.Descriptor instead.
func (*CustomerRegistration) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerRegistration) GetMrid() string {
	if x != nil {
		return x.Mrid
	}
	return ""
}

func (x *CustomerRegistration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerRegistration) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CustomerRegistration) GetMembershipStatus() string {
	if x != nil {
		return x.MembershipStatus
	}
	return ""
}

func (x *CustomerRegistration) GetContractNumber() string {
	if x != nil {
		return x.ContractNumber
	}
	return ""
}

func (x *CustomerRegistration) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type SettlementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`                                  // Start of the billing period (RFC 3339)
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`                                      // End of the billing period (RFC 3339)
	CommunityId   string                 `protobuf:"bytes,3,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"` // Community the requesting manager settles (empty: legacy, unscoped)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementRequest) Reset() {
	*x = SettlementRequest{}
	mi := &file_idssschema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementRequest) ProtoMessage() {}

func (x *SettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementRequest.ProtoReflect.Descriptor instead.
func (*SettlementRequest) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{2}
}

func (x *SettlementRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SettlementRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SettlementRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type SettlementResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                                // The peer ID of the node
	MeterReadingSum float64                `protobuf:"fixed64,2,opt,name=meter_reading_sum,json=meterReadingSum,proto3" json:"meter_reading_sum,omitempty"` // The sum of meter readings
	TradeVolumeSum  float64                `protobuf:"fixed64,3,opt,name=trade_volume_sum,json=tradeVolumeSum,proto3" json:"trade_volume_sum,omitempty"`    // The sum of trade volumes
	CommunityId     string                 `protobuf:"bytes,4,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`                 // Community of the responding peer (scoped settlement only)
	Refusal         string                 `protobuf:"bytes,5,opt,name=refusal,proto3" json:"refusal,omitempty"`                                            // Non-empty when the peer refused the request, with the reason
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SettlementResult) Reset() {
	*x = SettlementResult{}
	mi := &file_idssschema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementResult) ProtoMessage() {}

func (x *SettlementResult) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementResult.ProtoReflect.Descriptor instead.
func (*SettlementResult) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{3}
}

func (x *SettlementResult) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SettlementResult) GetMeterReadingSum() float64 {
	if x != nil {
		return x.MeterReadingSum
	}
	return 0
}

func (x *SettlementResult) GetTradeVolumeSum() float64 {
	if x != nil {
		return x.TradeVolumeSum
	}
	return 0
}

func (x *SettlementResult) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *SettlementResult) GetRefusal() string {
	if x != nil {
		return x.Refusal
	}
	return ""
}

type QueryState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         QueryState_State       `protobuf:"varint,1,opt,name=state,proto3,enum=common.QueryState_State" json:"state,omitempty"`
	Result        []*Row                 `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"` // Optional, to store intermediate/final results if needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryState) Reset() {
	*x = QueryState{}
	mi := &file_idssschema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryState) ProtoMessage() {}

func (x *QueryState) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryState.ProtoReflect.Descriptor instead.
func (*QueryState) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{4}
}

func (x *QueryState) GetState() QueryState_State {
	if x != nil {
		return x.State
	}
	return QueryState_QUEUED
}

func (x *QueryState) GetResult() []*Row {
	if x != nil {
		return x.Result
	}
	return nil
}

// Row represents a single row in the query result
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []string               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_idssschema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{5}
}

func (x *Row) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_idssschema_proto protoreflect.FileDescriptor

const file_idssschema_proto_rawDesc = "" +
	"\n" +
	"\x10idssschema.proto\x12\x06common\"\xc7\x05\n" +
	"\fQueryMessage\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.common.MessageTypeR\x04type\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04uqid\x18\x03 \x01(\tR\x04uqid\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\tR\ttimestamp\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x02R\x03ttl\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12\x1e\n" +
	"\n" +
	"originator\x18\x06 \x01(\tR\n" +
	"originator\x12(\n" +
	"\x05state\x18\a \x01(\v2\x12.common.QueryStateR\x05state\x12\x16\n" +
	"\x06labels\x18\b \x03(\tR\x06labels\x12#\n" +
	"\x06result\x18\t \x03(\v2\v.common.RowR\x06result\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12!\n" +
	"\frecord_count\x18\f \x01(\x05R\vrecordCount\x12!\n" +
	"\frequester_id\x18\r \x01(\tR\vrequesterId\x12%\n" +
	"\x0erequester_role\x18\x0e \x01(\tR\rrequesterRole\x12Q\n" +
	"\x15customer_registration\x18\x0f \x01(\v2\x1c.common.CustomerRegistrationR\x14customerRegistration\x12H\n" +
	"\x12settlement_request\x18\x10 \x01(\v2\x19.common.SettlementRequestR\x11settlementRequest\x12E\n" +
	"\x11settlement_result\x18\x11 \x01(\v2\x18.common.SettlementResultR\x10settlementResult\x12.\n" +
	"\x13responding_peer_ids\x18\x12 \x03(\tR\x11respondingPeerIds\"\xcb\x01\n" +
	"\x14CustomerRegistration\x12\x12\n" +
	"\x04mrid\x18\x01 \x01(\tR\x04mrid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12+\n" +
	"\x11membership_status\x18\x04 \x01(\tR\x10membershipStatus\x12'\n" +
	"\x0fcontract_number\x18\x05 \x01(\tR\x0econtractNumber\x12!\n" +
	"\fcommunity_id\x18\x06 \x01(\tR\vcommunityId\"Z\n" +
	"\x11SettlementRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12!\n" +
	"\fcommunity_id\x18\x03 \x01(\tR\vcommunityId\"\xbe\x01\n" +
	"\x10SettlementResult\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12*\n" +
	"\x11meter_reading_sum\x18\x02 \x01(\x01R\x0fmeterReadingSum\x12(\n" +
	"\x10trade_volume_sum\x18\x03 \x01(\x01R\x0etradeVolumeSum\x12!\n" +
	"\fcommunity_id\x18\x04 \x01(\tR\vcommunityId\x12\x18\n" +
	"\arefusal\x18\x05 \x01(\tR\arefusal\"\xb6\x01\n" +
	"\n" +
	"QueryState\x12.\n" +
	"\x05state\x18\x01 \x01(\x0e2\x18.common.QueryState.StateR\x05state\x12#\n" +
	"\x06result\x18\x02 \x03(\v2\v.common.RowR\x06result\"S\n" +
	"\x05State\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\x14\n" +
	"\x10LOCALLY_EXECUTED\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\r\n" +
	"\tSENT_BACK\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\"\x19\n" +
	"\x03Row\x12\x12\n" +
	"\x04data\x18\x01 \x03(\tR\x04data*\x84\x01\n" +
	"\vMessageType\x12\t\n" +
	"\x05QUERY\x10\x00\x12\n" +
	"\n" +
	"\x06RESULT\x10\x01\x12\x19\n" +
	"\x15CUSTOMER_REGISTRATION\x10\x02\x12\x16\n" +
	"\x12SETTLEMENT_REQUEST\x10\x03\x12\x15\n" +
	"\x11SETTLEMENT_RESULT\x10\x04\x12\x14\n" +
	"\x10REGISTRATION_ACK\x10\x05B\x15Z\x13idss/graphdb/commonb\x06proto3"

var (
	file_idssschema_proto_rawDescOnce sync.Once
	file_idssschema_proto_rawDescData []byte
)

func file_idssschema_proto_rawDescGZIP() []byte {
	file_idssschema_proto_rawDescOnce.Do(func() {
		file_idssschema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idssschema_proto_rawDesc), len(file_idssschema_proto_rawDesc)))
	})
	return file_idssschema_proto_rawDescData
}

var file_idssschema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_idssschema_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_idssschema_proto_goTypes = []any{
	(MessageType)(0),             // 0: common.MessageType
	(QueryState_State)(0),        // 1: common.QueryState.State
	(*QueryMessage)(nil),         // 2: common.QueryMessage
	(*CustomerRegistration)(nil), // 3: common.CustomerRegistration
	(*SettlementRequest)(nil),    // 4: common.SettlementRequest
	(*SettlementResult)(nil),     // 5: common.SettlementResult
	(*QueryState)(nil),           // 6: common.QueryState
	(*Row)(nil),                  // 7: common.Row
}
var file_idssschema_proto_depIdxs = []int32{
	0, // 0: common.QueryMessage.type:type_name -> common.MessageType
	6, // 1: common.QueryMessage.state:type_name -> common.QueryState
	7, // 2: common.QueryMessage.result:type_name -> common.Row
	3, // 3: common.QueryMessage.customer_registration:type_name -> common.CustomerRegistration
	4, // 4: common.QueryMessage.settlement_request:type_name -> common.SettlementRequest
	5, // 5: common.QueryMessage.settlement_result:type_name -> common.SettlementResult
	1, // 6: common.QueryState.state:type_name -> common.QueryState.State
	7, // 7: common.QueryState.result:type_name -> common.Row
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_idssschema_proto_init() }
func file_idssschema_proto_init() {
	if File_idssschema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idssschema_proto_rawDesc), len(file_idssschema_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idssschema_proto_goTypes,
		DependencyIndexes: file_idssschema_proto_depIdxs,
		EnumInfos:         file_idssschema_proto_enumTypes,
		MessageInfos:      file_idssschema_proto_msgTypes,
	}.Build()
	File_idssschema_proto = out.File
	file_idssschema_proto_goTypes = nil
	file_idssschema_proto_depIdxs = nil
}
