// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: idssschema.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_QUERY  MessageType = 0
	MessageType_RESULT MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "QUERY",
		1: "RESULT",
	}
	MessageType_value = map[string]int32{
		"QUERY":  0,
		"RESULT": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_idssschema_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_idssschema_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{0}
}

type QueryState_State int32

const (
	QueryState_QUEUED           QueryState_State = 0 // The query is in the queue
	QueryState_LOCALLY_EXECUTED QueryState_State = 1 // The query is executed locally
	QueryState_COMPLETED        QueryState_State = 2 // The query is completed
	QueryState_SENT_BACK        QueryState_State = 3 // Query result is sent back to the parent node
	QueryState_FAILED           QueryState_State = 4 // The query failed
)

// Enum value maps for QueryState_State.
var (
	QueryState_State_name = map[int32]string{
		0: "QUEUED",
		1: "LOCALLY_EXECUTED",
		2: "COMPLETED",
		3: "SENT_BACK",
		4: "FAILED",
	}
	QueryState_State_value = map[string]int32{
		"QUEUED":           0,
		"LOCALLY_EXECUTED": 1,
		"COMPLETED":        2,
		"SENT_BACK":        3,
		"FAILED":           4,
	}
)

func (x QueryState_State) Enum() *QueryState_State {
	p := new(QueryState_State)
	*p = x
	return p
}

func (x QueryState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_idssschema_proto_enumTypes[1].Descriptor()
}

func (QueryState_State) Type() protoreflect.EnumType {
	return &file_idssschema_proto_enumTypes[1]
}

func (x QueryState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryState_State.Descriptor instead.
func (QueryState_State) EnumDescriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{1, 0}
}

// QueryMessage represents a query being propagated in the network
type QueryMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=common.MessageType" json:"type,omitempty"` // To distinguish between QUERY and RESULT.
	Query      string      `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                        // The query to be executed
	Uqi        string      `protobuf:"bytes,3,opt,name=uqi,proto3" json:"uqi,omitempty"`                            // Unique Query Identifier
	Ttl        float32     `protobuf:"fixed32,4,opt,name=ttl,proto3" json:"ttl,omitempty"`                          // Time to live
	Sender     string      `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`                      // The peer_id of the sender
	Originator string      `protobuf:"bytes,6,opt,name=originator,proto3" json:"originator,omitempty"`              // The peer_id of the originator
	State      *QueryState `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`                        // The state of the query
	Labels     []string    `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`                      // The labels of the query
	Result     []*Row      `protobuf:"bytes,9,rep,name=result,proto3" json:"result,omitempty"`                      // The result of the query
	Error      string      `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`                       // Error message if any
}

func (x *QueryMessage) Reset() {
	*x = QueryMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idssschema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMessage) ProtoMessage() {}

func (x *QueryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMessage.ProtoReflect.Descriptor instead.
func (*QueryMessage) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_QUERY
}

func (x *QueryMessage) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryMessage) GetUqi() string {
	if x != nil {
		return x.Uqi
	}
	return ""
}

func (x *QueryMessage) GetTtl() float32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *QueryMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *QueryMessage) GetOriginator() string {
	if x != nil {
		return x.Originator
	}
	return ""
}

func (x *QueryMessage) GetState() *QueryState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *QueryMessage) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QueryMessage) GetResult() []*Row {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State  QueryState_State `protobuf:"varint,1,opt,name=state,proto3,enum=common.QueryState_State" json:"state,omitempty"`
	Result []*Row           `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"` // Optional, to store intermediate/final results if needed
}

func (x *QueryState) Reset() {
	*x = QueryState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idssschema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryState) ProtoMessage() {}

func (x *QueryState) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryState.ProtoReflect.Descriptor instead.
func (*QueryState) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{1}
}

func (x *QueryState) GetState() QueryState_State {
	if x != nil {
		return x.State
	}
	return QueryState_QUEUED
}

func (x *QueryState) GetResult() []*Row {
	if x != nil {
		return x.Result
	}
	return nil
}

// Row represents a single row in the query result
type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idssschema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_idssschema_proto protoreflect.FileDescriptor

var file_idssschema_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x64, 0x73, 0x73, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0xa6, 0x02, 0x0a, 0x0c, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x71,
	0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x71, 0x69, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x74, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0xb6, 0x01, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x77, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x53, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x4c, 0x59, 0x5f, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45, 0x4e, 0x54, 0x5f, 0x42, 0x41, 0x43, 0x4b, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x22, 0x19, 0x0a, 0x03,
	0x52, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x24, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x01, 0x42, 0x15, 0x5a,
	0x13, 0x69, 0x64, 0x73, 0x73, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x64, 0x62, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idssschema_proto_rawDescOnce sync.Once
	file_idssschema_proto_rawDescData = file_idssschema_proto_rawDesc
)

func file_idssschema_proto_rawDescGZIP() []byte {
	file_idssschema_proto_rawDescOnce.Do(func() {
		file_idssschema_proto_rawDescData = protoimpl.X.CompressGZIP(file_idssschema_proto_rawDescData)
	})
	return file_idssschema_proto_rawDescData
}

var file_idssschema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_idssschema_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_idssschema_proto_goTypes = []any{
	(MessageType)(0),      // 0: common.MessageType
	(QueryState_State)(0), // 1: common.QueryState.State
	(*QueryMessage)(nil),  // 2: common.QueryMessage
	(*QueryState)(nil),    // 3: common.QueryState
	(*Row)(nil),           // 4: common.Row
}
var file_idssschema_proto_depIdxs = []int32{
	0, // 0: common.QueryMessage.type:type_name -> common.MessageType
	3, // 1: common.QueryMessage.state:type_name -> common.QueryState
	4, // 2: common.QueryMessage.result:type_name -> common.Row
	1, // 3: common.QueryState.state:type_name -> common.QueryState.State
	4, // 4: common.QueryState.result:type_name -> common.Row
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_idssschema_proto_init() }
func file_idssschema_proto_init() {
	if File_idssschema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idssschema_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*QueryMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idssschema_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*QueryState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idssschema_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idssschema_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idssschema_proto_goTypes,
		DependencyIndexes: file_idssschema_proto_depIdxs,
		EnumInfos:         file_idssschema_proto_enumTypes,
		MessageInfos:      file_idssschema_proto_msgTypes,
	}.Build()
	File_idssschema_proto = out.File
	file_idssschema_proto_rawDesc = nil
	file_idssschema_proto_goTypes = nil
	file_idssschema_proto_depIdxs = nil
}
